language: python
python:
  - "3.9"

services:
  - docker

install:
  - pip install pipenv
  - pipenv lock --keep-outdated --requirements > requirements.txt
  - pip install -r /tmp/requirements.txt

script:
  - python -m pytest tests/
