language: python
python:
  - "3.9"

install:
  - pip install pipenv
  - pipenv lock --keep-outdated --requirements > requirements.txt
  - pip install -r requirements.txt

script:
  - python -m pytest tests/
